Curated Package Documentation
aws/eks-anywhere pull request #1893
Opened 2022-04-20 18:55 UTC by vincentni

*Issue #, if available:*

*Description of changes:*

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-04-20 19:06 UTC, vincentni commented on docs/content/en/docs/tasks/packages/_index.md
> +The main goal of EKS Anywhere curated packages is to make it easy to install, configure and maintain operational components in an EKS Anywhere cluster. EKS Anywhere curated packages offers to run sec
This needs to be updated to link to the page under https://github.com/aws/eks-anywhere/pull/1877.

2022-04-22 15:28 UTC, TerryHowe requested changes
I have more, this is a start

2022-04-22 15:28 UTC, TerryHowe commented on docs/content/en/docs/getting-started/local-environment/_index.md
> +   * It is *optional* to install the curated packages as part of the cluster creation and `eksctl anywhere` version should be `v0.9.0` or later.
```suggestion
   * It is *optional* to install the curated packages as part of the cluster creation
   * `eksctl anywhere version` version should be `v0.9.0` or later.
```

2022-04-22 15:28 UTC, TerryHowe commented on docs/content/en/docs/getting-started/local-environment/_index.md
> +   Example shows how to install two packages `flux` and `harbor` from the [curated package list]({{< relref "../../reference/packagespec" >}}).
```suggestion
   Example shows how to install two packages `harbor` from the [curated package list]({{< relref "../../reference/packagespec" >}}).
```

2022-04-22 15:28 UTC, TerryHowe commented on docs/content/en/docs/getting-started/local-environment/_index.md
> +   eksctl anywhere generate package flux harbor -d .
```suggestion
   eksctl anywhere generate package harbor -d .
```

2022-04-22 15:28 UTC, TerryHowe commented on docs/content/en/docs/getting-started/local-environment/_index.md
> +   eksctl anywhere create cluster -f $CLUSTER_NAME.yaml --install-packages ./curated-packages/
Can't we use a default directory here. I think the packages directory would have to be pretty much hard coded for gitops

2022-04-22 15:28 UTC, TerryHowe commented on docs/content/en/docs/getting-started/local-environment/_index.md
> +* See the [Package management]({{< relref "../../tasks/packages" >}}) section with more information on post-creation curated packages installation.
```suggestion
* See the [Package management]({{< relref "../../tasks/packages" >}}) section for more information on post-creation curated packages installation.
```

2022-04-22 15:28 UTC, TerryHowe commented on docs/content/en/docs/getting-started/local-environment/_index.md
> +   Example shows how to install two packages `flux` and `harbor` from the [curated package list]({{< relref "../../reference/packagespec" >}}).
We aren't supporting flux as far as I know. Same comment applies to prod section below

2022-04-22 15:28 UTC, TerryHowe commented on docs/content/en/docs/tasks/packages/harbor/_index.md
> +   eksctl anywhere generate package Harbor --source cluster -d .
```suggestion
   eksctl anywhere generate package harbor --source cluster -d .
```
This should be all case insensitive

2022-04-22 16:07 UTC, ewollesen reviewed
WOW! Great job Vincent! This was a _TON_ of good work!

I can't leave a comment directly, but in `docs/static/images/harbor-private_proxy_project.png`, `docs/static/images/harbor-replication_result.png`, and `docs/static/images/harbor-replication_rule.png` an account ID is visible. It should probably be blurred out.

2022-04-22 16:07 UTC, ewollesen commented on docs/content/en/docs/workshops/introduction/harbor.md
> +This use case is to use Harbor to replicate local images and charts to a private ECR repository in a push mode. When a replication rule is set, all resources that match the defined filter patterns ar
```suggestion
This use case is to use Harbor to replicate local images and charts to a private ECR repository in push mode. When a replication rule is set, all resources that match the defined filter patterns are replicated to the destination registry when the triggering condition is met.
```

2022-04-22 16:07 UTC, ewollesen commented on docs/content/en/docs/workshops/introduction/harbor.md
> +   * `harbor.eksa.demo:30003` should be replaced with whatever `externalURL` is set to in the Harbor package yaml file.
```suggestion
   * `harbor.eksa.demo:30003` should be replaced with whatever `externalURL` is set to in the Harbor package YAML file.
```
This is a little detail, but YAML is an acronym, so anywhere in the document that you're not using YAML as part of a filename, it should be capitalized. I mean, people are gonna know what you mean either way, but it looks more professional/better capitalized.

2022-04-23 12:42 UTC, TerryHowe commented
BTW, you can just commit the suggestions and git pull your branch locally to get all the updates. That would make our reviewing easier for this large PR

2022-04-23 12:53 UTC, TerryHowe commented on docs/content/en/docs/tasks/packages/harbor/_index.md
> +To install package controller, please follow the [installation guide.]({{< relref ".." >}})
I don't think this needs to be an alert 
```suggestion
If your cluster was created with a release of EKS Anywhere prior to 0.9.0, you may need to [installation the package controller.]({{< relref ".." >}})
```

2022-04-29 20:30 UTC, chrisnegus reviewed
Good content! I have a few suggestions.

2022-04-29 20:30 UTC, chrisnegus commented on docs/content/en/docs/tasks/packages/_index.md
> +* To install EKS Anywhere, create an EKS Anywhere cluster, or review the EKS Anywhere system requirements, see the [getting-started guide.]({{< relref "../../getting-started" >}})
```suggestion
* To install EKS Anywhere, create an EKS Anywhere cluster or review the EKS Anywhere system requirements.
See the [Getting started]({{< relref "../../getting-started" >}}) guide for details.
```

2022-04-29 20:30 UTC, chrisnegus commented on docs/content/en/docs/tasks/packages/harbor/_index.md
> +   * `secretKey` has to be set as a string of 16 chars for encryption.
```suggestion
   * `secretKey` has to be set as a string of 16 characters for encryption.
```

2022-04-29 20:30 UTC, chrisnegus commented on docs/content/en/docs/workshops/introduction/harbor.md
> +    Navigate to `Registries` on the left panel, and then click on `NEW ENDPOINT` button. Choose `Docker Registry` as Provider, and enter `public-ecr` as Name, `https://public.ecr.aws/` as Endpoint UR
```suggestion
    Navigate to `Registries` on the left panel, and then click on `NEW ENDPOINT` button. Choose `Docker Registry` as the Provider, enter `public-ecr` as the Name, and enter `https://public.ecr.aws/` as the Endpoint URL. Save it by clicking on OK.
```

2022-04-29 20:30 UTC, chrisnegus commented on docs/content/en/docs/workshops/introduction/harbor.md
> +    Navigate to `Projects` on the left panel and click on `NEW PROJECT` button. Enter `proxy-project` as Project Name, check `Public access level`, and turn on Proxy Cache and choose `public-ecr` fro
```suggestion
    Navigate to `Projects` on the left panel and click on the `NEW PROJECT` button. Enter `proxy-project` as the Project Name, check `Public access level`, turn on Proxy Cache and choose `public-ecr` from the pull-down list. Save the configuration by clicking on OK.
```

2022-04-29 20:30 UTC, chrisnegus commented on docs/content/en/docs/workshops/introduction/harbor.md
> +        This is where you specify all necessary permissions and please refer to [private repository policies](https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-policies.html), [IAM pe
```suggestion
        This is where you specify all necessary permissions. Please refer to [private repository policies](https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-policies.html), [IAM permissions for pushing an image](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-push.html) and [ECR policy examples](https://docs.aws.amazon.com/AmazonECR/latest/userguide/security_iam_id-based-policy-examples.html) to figure out the minimal set of required permissions.
```

2022-04-29 20:30 UTC, chrisnegus commented on docs/content/en/docs/workshops/introduction/harbor.md
> +        This is where you specify all necessary permissions and please refer to [private repository policies](https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-policies.html), [IAM pe
```suggestion
        This is where you specify all necessary permissions. Please refer to [private repository policies](https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-policies.html), [IAM permissions for pushing an image](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-push.html) and [ECR policy examples](https://docs.aws.amazon.com/AmazonECR/latest/userguide/security_iam_id-based-policy-examples.html) to figure out the minimal set of required permissions.
```

2022-04-29 20:30 UTC, chrisnegus commented on docs/content/en/docs/workshops/introduction/harbor.md
> +    Navigate to `Registries` on the left panel, and then click on `NEW ENDPOINT` button. Choose `Aws ECR` as Provider, and enter `private-ecr` as Name, `https://[ACCOUNT NUMBER].dkr.ecr.us-west-2.ama
```suggestion
    Navigate to `Registries` on the left panel, and then click on the `NEW ENDPOINT` button. Choose `Aws ECR` as the Provider, enter `private-ecr` as the Name, and `https://[ACCOUNT NUMBER].dkr.ecr.us-west-2.amazonaws.com/` as the Endpoint URL, use the access key ID part of the generated access key as Access ID, and use the secret access key part of the generated access key as Access Secret. Save it by clicking on OK.
```

2022-05-10 15:42 UTC, TerryHowe commented on docs/content/en/docs/tasks/packages/_index.md
> +* Check if the version of `eksctl anywhere` is above `v0.9.0` with the following commands:
```suggestion
* Check if the version of `eksctl anywhere` is `v0.9.0` or above with the following commands:
```

2022-05-10 20:02 UTC, chrisnegus approved these changes
/lgtm

2022-05-10 20:02 UTC, TerryHowe commented
/cherry-pick release-0.9

2022-05-10 20:04 UTC, merged