Read cidr blocks from the cluster config file for docker
aws/eks-anywhere pull request #268
Opened 2021-09-21 17:26 UTC by bnrjee

*Issue #, if available:*

*Description of changes:*
At the moment, the pod and service cidr values are all hard coded for docker. With this change, these values will be read from the cluster spec file.
Test output result:

`3c22fbf0706c:eks-anywhere bnrjee$ kubectl cluster-info dump --kubeconfig abc/abc-eks-a-cluster.kubeconfig | grep -i cidr
                    "io.cilium.network.ipv4-pod-cidr": "10.10.1.0/24",
                "podCIDR": "10.10.1.0/24",
                "podCIDRs": [
                    "io.cilium.network.ipv4-pod-cidr": "10.10.0.0/24",
                "podCIDR": "10.10.0.0/24",
                "podCIDRs": [
                            "--allocate-node-cidrs=true",
                            "--cluster-cidr=10.10.0.0/16",
I0921 17:04:45.014930       1 range_allocator.go:116] No Secondary Service CIDR provided. Skipping filtering out secondary service addresses.
I0921 17:04:45.115527       1 range_allocator.go:172] Starting range CIDR allocator
I0921 17:04:45.115532       1 shared_informer.go:240] Waiting for caches to sync for cidrallocator
I0921 17:04:45.115535       1 shared_informer.go:247] Caches are synced for cidrallocator 
I0921 17:04:45.120349       1 range_allocator.go:373] Set node abc-sn6jz PodCIDR to [10.10.0.0/24]
I0921 17:04:51.571683       1 range_allocator.go:373] Set node abc-md-0-85c9ccb857-vt6pw PodCIDR to [10.10.1.0/24]
W0921 17:04:47.239883       1 server_others.go:512] detect-local-mode set to ClusterCIDR, but no IPv6 cluster CIDR defined, , defaulting to no-op detect-local for IPv6
W0921 17:04:59.054069       1 server_others.go:512] detect-local-mode set to ClusterCIDR, but no IPv6 cluster CIDR defined, , defaulting to no-op detect-local for IPv6`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-09-21 17:31 UTC, g-gaston requested changes
I'm surprised we don't have a test case for that
Can we update the current ones/add a new one?

2021-09-21 17:33 UTC, abhay-krishna commented
/ok-to-test

2021-09-21 18:36 UTC, abhay-krishna commented
/retest

2021-09-22 17:12 UTC, bnrjee commented
/test eks-anywhere-cluster-controller-tooling-presubmit

2021-09-22 17:48 UTC, g-gaston approved these changes

2021-09-22 17:48 UTC, g-gaston commented on pkg/providers/docker/docker_test.go
> +				s.Spec.ClusterNetwork.Services.CidrBlocks = []string{"192.168.0.0/16"}
can we add multiple blocks in this test?

2021-09-22 18:36 UTC, jiayiwang7 approved these changes

2021-09-22 19:14 UTC, TerryHowe approved these changes
/lgtm

2021-09-22 19:35 UTC, merged