Adding token refreshser to EKS-A release bundle
aws/eks-anywhere pull request #2939
Opened 2022-08-15 22:02 UTC by jonahjon

Signed-off-by: jonahjon <jonahjones094@gmail.com>

Current tests are failing  since the new image isn't being pushed to Public ECR. This is adding it to the bundle.

2022-08-15 22:28 UTC, jonahjon commented
/cherrypick release-0.11

2022-08-15 22:31 UTC, abhay-krishna commented on release/api/v1alpha1/bundle_types.go
> +	Refreshser Image  `json:"tokenRefresher"`
typo
```suggestion
	Refresher Image  `json:"tokenRefresher"`
```

2022-08-15 22:32 UTC, abhay-krishna commented on release/api/v1alpha1/bundle_types.go
> +	Refreshser Image  `json:"tokenRefresher"`
I would actually prefer to use `TokenRefresher` as the field name to make intentions clear.

2022-08-16 18:01 UTC, TerryHowe commented
conflicts!

2022-08-16 18:04 UTC, TerryHowe commented
I resolved the conflicts

2022-08-16 18:06 UTC, TerryHowe commented on config/crd/bases/anywhere.eks.amazonaws.com_cloudstackdatacenterconfigs.yaml
>                account:
This change looks like it shouldn't be here

2022-08-16 18:06 UTC, TerryHowe commented on config/manifest/eksa-components.yaml
>                account:
and these changes

2022-08-16 18:18 UTC, TerryHowe commented on config/crd/bases/anywhere.eks.amazonaws.com_cloudstackdatacenterconfigs.yaml
>                account:
It would be nice to get rid of these cloudstack changes.

2022-08-16 18:18 UTC, TerryHowe commented
tests borked

2022-08-16 18:46 UTC, jonahjon commented
/test eks-anywhere-presubmit

2022-08-16 18:52 UTC, jonahjon commented
Looks to be an issue due to a recent cloudtstack PR https://github.com/aws/eks-anywhere-build-tooling/pull/1170

2022-08-16 18:53 UTC, a-cool-train commented on release/pkg/bundles/package-controller.go
> +	//artifacts := r.BundleArtifactsTable["eks-anywhere-packages"]
Can we remove this from the code if it is not necessary?

2022-08-16 18:54 UTC, a-cool-train requested changes
@jonahjon, we need to also extract the ecr refresher cron job in case of download images and import images. This is to support the disconnected area.

2022-08-16 18:57 UTC, jonahjon commented
> @jonahjon, we need to also extract the ecr refresher cron job in case of download images and import images. This is to support the disconnected area.

What does that mean?

2022-08-16 19:12 UTC, jonahjon commented
/retest

2022-08-16 19:15 UTC, jonahjon commented
> @jonahjon, we need to also extract the ecr refresher cron job in case of download images and import images. This is to support the disconnected area.

Also can we just do that in another PR since this one is blocking the release pipeline.

2022-08-16 19:21 UTC, jonahjon commented
/retest

2022-08-16 19:54 UTC, jonahjon commented
/retest

2022-08-16 20:00 UTC, jonahjon commented
/override eks-anywhere-release-tooling-presubmit

2022-08-16 20:00 UTC, jonahjon commented
/override eks-anywhere-release-tooling-test-presubmit

2022-08-16 20:17 UTC, jonahjon commented
/override eks-anywhere-release-tooling-presubmit

2022-08-16 20:34 UTC, abhay-krishna commented
/lgtm
/approve

2022-08-16 20:51 UTC, jonahjon commented
![tide](https://user-images.githubusercontent.com/34656423/184982713-a2379800-e8f4-433f-86ad-b78e465f95b6.jpeg)

2022-08-16 20:53 UTC, jonahjon commented
Why prow decides to re-test 7 jobs that passed a few minutes ago is a mystery to me.

2022-08-16 21:05 UTC, jonahjon commented
/test eks-anywhere-presubmit

2022-08-16 21:16 UTC, merged