Skip installing curated packages when no license info is provided.
aws/eks-anywhere pull request #3850
Opened 2022-10-29 18:50 UTC by wongni

*Issue #, if available:* #3829

*Description of changes:*
Skip installing the curated packages when no license info is provided

*Testing (if applicable):*
Unit testing and e2e testing

```
2022-10-28T20:51:06.431-0500    V0      🎉 Cluster created!
2022-10-28T20:51:06.431-0500    V4      Task finished   {"task_name": "delete-kind-cluster", "duration": "12.581401292s"}
2022-10-28T20:51:06.431-0500    V4      ----------------------------------
2022-10-28T20:51:06.432-0500    V4      Task start      {"task_name": "install-curated-packages"}
2022-10-28T20:51:06.432-0500    V0      ⚠️Installing curated packages is skipped
2022-10-28T20:51:06.432-0500    V4      Task finished   {"task_name": "install-curated-packages", "duration": "258.949µs"}
2022-10-28T20:51:06.432-0500    V4      ----------------------------------
2022-10-28T20:51:06.432-0500    V4      Tasks completed {"duration": "10m2.688560109s"}
2022-10-28T20:51:06.464-0500    V3      Cleaning up long running container      {"name": "eksa_1667007645532228000"}
2022-10-28T20:51:06.466-0500    V6      Executing command       {"cmd": "/usr/local/bin/docker rm -f -v eksa_1667007645532228000"}
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-10-30 13:18 UTC, TerryHowe requested changes
Discuss this with Lichun

2022-11-01 17:48 UTC, maxdrib commented on pkg/curatedpackages/packagecontrollerclient.go
> +func (pc *PackageControllerClient) CanCuratedPackagesEnabled(ctx context.Context) bool {
```suggestion
func (pc *PackageControllerClient) CanCuratedPackagesBeEnabled(ctx context.Context) bool {
```

2022-11-01 18:28 UTC, a-cool-train requested changes
Let's get some suggestions from Lichun.

2022-11-01 18:31 UTC, wongni commented
The customer wants to have an explicit flag to skip the installation of the curated packages because they want to still skip it even if licensed.

2022-11-02 21:12 UTC, closed without merging