Update docs for 1.25
aws/eks-anywhere pull request #4924
Opened 2023-02-13 16:50 UTC by taneyland

*Issue #, if available:*

*Description of changes:*

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-02-13 17:52 UTC, chrisnegus commented on docs/content/en/docs/reference/clusterspec/snow.md
> +Replaces the default control plane taint (For k8s versions prior to 1.24, `node-role.kubernetes.io/master`. For k8s versions 1.24+, `node-role.kubernetes.io/control-plane`).. The default control plan
```suggestion
Replaces the default control plane taint. For k8s versions prior to 1.24, it replaces `node-role.kubernetes.io/master`. For k8s versions 1.24+, it replaces `node-role.kubernetes.io/control-plane`. The default control plane components will tolerate the provided taints.
```

2023-02-13 17:55 UTC, chrisnegus requested changes
Looks good. Just one suggestion (x2) about rewording the new taints description. If you don't like my wording, maybe try something else.

2023-02-13 17:55 UTC, chrisnegus commented on docs/content/en/docs/reference/clusterspec/snow.md
> +Replaces the default control plane taint (For k8s versions prior to 1.24, `node-role.kubernetes.io/master`. For k8s versions 1.24+, `node-role.kubernetes.io/control-plane`).. The default control plan
```suggestion
Replaces the default control plane taint. For k8s versions prior to 1.24, it replaces `node-role.kubernetes.io/master`. For k8s versions 1.24+, it replaces `node-role.kubernetes.io/control-plane`. The default control plane components will tolerate the provided taints.
```

2023-02-13 17:55 UTC, chrisnegus commented on docs/content/en/docs/reference/clusterspec/vsphere.md
> +Replaces the default control plane taint (For k8s versions prior to 1.24, `node-role.kubernetes.io/master`. For k8s versions 1.24+, `node-role.kubernetes.io/control-plane`). The default control plane
```suggestion
Replaces the default control plane taint. For k8s versions prior to 1.24, it replaces `node-role.kubernetes.io/master`. For k8s versions 1.24+, it replaces `node-role.kubernetes.io/control-plane`. The default control plane components will tolerate the provided taints.
```

2023-02-13 19:23 UTC, chrisnegus commented
/lgtm

2023-02-14 01:13 UTC, vivek-koppuru reviewed
Can we replace the 1.23 references with 1.25 here on this page? https://anywhere.eks.amazonaws.com/docs/reference/vsphere/vsphere-ovas/

2023-02-14 16:42 UTC, vivek-koppuru approved these changes

2023-02-14 17:00 UTC, merged