Add egress-masquerade-interfaces option to cilium
aws/eks-anywhere pull request #6018
Opened 2023-06-12 22:49 UTC by ahreehong

*Issue #, if available:*

*Description of changes:*

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-06-14 23:00 UTC, jacobweinstock requested changes

2023-06-14 23:05 UTC, ahreehong commented on pkg/networking/cilium/upgrader_test.go
> +	// tt.newSpec.Cluster.Spec.ClusterNetwork.CNIConfig.Cilium.EgressMasqueradeInterfaces = "test"
Yeah, I missed this when I was cleaning up the code. Will remove

2023-06-14 23:06 UTC, ahreehong commented on config/manifest/eksa-components.yaml
> +        image: public.ecr.aws/l0g8r8j6/eks-anywhere-cluster-controller:v0.16.0-eks-a-v0.0.0-dev-build.7080
Yeah this is left over from local testing. I'm not sure if this value should be updated though, `public.ecr.aws/l0g8r8j6/eks-anywhere-cluster-controller:v0.0.0-eks-a-v0.0.0-dev-build.251` seems like an ancient build

2023-06-15 16:11 UTC, ahreehong commented
/retest

2023-06-15 20:23 UTC, ahreehong commented on config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml
> +                              values are strings.
test

2023-06-15 21:08 UTC, jacobweinstock approved these changes
thanks for the patience and work on this! @ahreehong

2023-06-15 21:18 UTC, ahreehong commented
/approve

2023-06-15 21:26 UTC, merged