replace multi yaml file parsing via yaml separator
aws/eks-anywhere pull request #6170
Opened 2023-07-13 15:29 UTC by HiteshRepo

*Issue #, if available:*
Yaml separator '---' was used to split and read a multi yaml manifests.
The yaml manifests might contain certificate data which might lead to erroneous results.

*Description of changes:*
Replacing the parsing logic using yaml util library ("k8s.io/apimachinery/pkg/util/yaml")

2023-07-17 06:05 UTC, HiteshRepo commented
@chrisdoherty4 could you please take a look at this?

2023-08-17 20:38 UTC, chrisdoherty4 requested changes
Thank you for the submission @HiteshRepo. Apologies for the delay, again. These are great improvements.

2023-08-17 20:38 UTC, chrisdoherty4 commented on pkg/api/v1alpha1/tinkerbellmachineconfig.go
> +	yamlutil "k8s.io/apimachinery/pkg/util/yaml"
```suggestion
	apimachineryyaml "k8s.io/apimachinery/pkg/util/yaml"
```

2023-08-17 20:38 UTC, chrisdoherty4 commented on pkg/yamlutil/parser.go
> +func ParseMultiYamlFile(fileName string) ([][]byte, error) {
Given this is a generic YAML parsing function it ought to live in `/pkg/utils/yaml`. This package, contrary to its name, isn't a set of generic YAML utils - apologies for the confusion.

2023-08-17 20:38 UTC, chrisdoherty4 commented on pkg/yamlutil/parser.go
> +func ParseMultiYamlFile(fileName string) ([][]byte, error) {
Can we accept an `io.Reader`? It makes the function compatible with non-file sources and simplifies testing as files aren't necessary.

The function can also be simplified to `SplitDocuments` particularly considering we aren't really parsing the file.

```go
func SplitDocuments(r io.Reader) ([][]byte, error) { ... }
```

```go
func main() {
	reader := ...
	yaml.SplitDocuments(reader)
}
```

2023-08-17 20:38 UTC, chrisdoherty4 commented on pkg/api/v1alpha1/tinkerbellmachineconfig.go
> +	yamlutilpkg "github.com/aws/eks-anywhere/pkg/yamlutil"
```suggestion
	"github.com/aws/eks-anywhere/pkg/yamlutil"
```

2023-09-01 16:50 UTC, chrisdoherty4 commented
Hi @HiteshRepo. Thank you for the changes, functionally everything looks great. The CI is complaining about a lack of function code comments and a compilation error (I think). Once that's fixed up this is good to go!

2023-09-03 23:14 UTC, chrisdoherty4 commented
/ok-to-test

2023-09-06 12:33 UTC, chrisdoherty4 commented
/lgtm
/approve

2023-09-06 13:54 UTC, chrisdoherty4 commented
/retest

2023-09-06 15:35 UTC, merged

2023-09-06 15:35 UTC, chrisdoherty4 commented
/cherry-pick release-0.17