check existence of machine config before further operations
aws/eks-anywhere pull request #6171
Opened 2023-07-13 15:54 UTC by HiteshRepo

*Issue #, if available:*
#6039 

*Description of changes:*
check existence of machine config before further operations

2023-07-15 15:10 UTC, HiteshRepo commented
/ok-to-test

2023-07-17 06:05 UTC, HiteshRepo commented
@chrisdoherty4 could you please take a look at this?

2023-08-03 13:41 UTC, chrisdoherty4 commented
@HiteshRepo Apologies for the slowness in the last few hectic weeks. We'll take a look shortly. 

/cc chrisdoherty4 jacobweinstock

2023-08-07 15:50 UTC, chrisdoherty4 commented on pkg/providers/tinkerbell/tinkerbell.go
> +	if _, ok := p.machineConfigs[controlPlaneMachineName]; ok {
I don't think we want to silently ignore the fact a machine config is missing. I think we can prevent this from ever happening by validating all machine configs are present in `NewProvider()`.

Specifically, on [L117](https://github.com/aws/eks-anywhere/blob/main/pkg/providers/tinkerbell/tinkerbell.go#L117) we `TinkebrellMachineConfig` spec but we don't handle it not being present.

2023-08-07 15:50 UTC, chrisdoherty4 requested changes
I don't think we want to silently ignore the fact a machine config is missing. I think we can prevent this from ever happening by validating all machine configs are present in NewProvider().

Specifically, on L117 we TinkebrellMachineConfig spec but we don't handle it not being present.

2023-08-17 20:44 UTC, chrisdoherty4 commented on pkg/providers/tinkerbell/tinkerbell.go
> +	if _, ok := p.machineConfigs[controlPlaneMachineName]; ok {
I think we can revert this change. If these machine configs are missing, there's a catastrophic problem and silently ignoring the fact may result in side effects with processes later on.

The checks added in `NewProvider` should be sufficient to protect against this issue now.

2023-08-17 20:45 UTC, chrisdoherty4 requested changes
@HiteshRepo thanks again. I've added 1 final comment regarding reverting the original changes.

2023-09-01 16:53 UTC, chrisdoherty4 commented
/ok-to-test

2023-09-01 16:53 UTC, chrisdoherty4 commented
/lgtm

2023-09-01 16:54 UTC, chrisdoherty4 commented
Looking great @HiteshRepo, thank you for your submissions.

2023-09-04 12:19 UTC, chrisdoherty4 commented
/lgtm

2023-09-05 13:36 UTC, chrisdoherty4 commented
/approve

2023-09-05 13:37 UTC, chrisdoherty4 approved these changes

2023-09-06 13:54 UTC, chrisdoherty4 commented
/retest

2023-09-06 15:36 UTC, merged

2023-09-06 15:36 UTC, chrisdoherty4 commented
/cherry-pick release-0.17