Add SANs configurability for API server
aws/eks-anywhere pull request #6921
Opened 2023-10-27 16:09 UTC by chrisdoherty4

To be written

2023-10-30 18:39 UTC, chrisdoherty4 commented
/approve

2023-11-01 19:05 UTC, tatlat requested changes
Why are we changing this?

2023-11-01 21:18 UTC, chrisdoherty4 commented
@tatlat Its been modified to include `sprig` functions instead of copying Helm and Sprig implementations. I wanted some additional functions for the templates.

2023-11-01 22:58 UTC, tatlat approved these changes

2023-11-01 23:22 UTC, merged