fix: docs to show apple and arm support
aws/eks-anywhere pull request #7067
Opened 2023-11-21 08:02 UTC by RazaGR

This fix the docs to show that eks now supports apple and arm processor. 

related issue https://github.com/aws/eks-anywhere/issues/182

2023-11-24 16:30 UTC, chrisnegus reviewed
A couple of punctuation suggestions.

2023-11-24 16:30 UTC, chrisnegus commented on docs/content/en/docs/getting-started/docker/_index.md
> +* EKS Anywhere works with x86 and amd64 architectures, From v0.18.1 it also works with Apple Silicon or Arm based processors.
```suggestion
* EKS Anywhere works with x86 and amd64 architectures. From v0.18.1, it also works with Apple Silicon or Arm based processors.
```

2023-11-24 16:30 UTC, chrisnegus commented on docs/content/en/docs/getting-started/install/_index.md
> +From v0.18.1 it also works with Apple Silicon or Arm based processors.
```suggestion
From v0.18.1, it also works with Apple Silicon or Arm based processors.
```

2023-11-27 14:46 UTC, chrisdoherty4 commented on docs/content/en/docs/getting-started/docker/_index.md
> +* EKS Anywhere works with x86 and amd64 architectures. From v0.18.1, it also works with Apple Silicon or Arm based processors.
```suggestion
* EKS Anywhere works with x86 and amd64 architectures. From v0.18.1, it also works with Apple Silicon or ARM based processors.
```

2023-11-27 14:46 UTC, chrisdoherty4 commented on docs/content/en/docs/getting-started/install/_index.md
>  {{% /alert %}}
We can remove this section now.

2023-11-27 14:47 UTC, chrisdoherty4 requested changes
Thanks for the updates. Some minor modifications.

2023-11-27 17:28 UTC, RazaGR commented on docs/content/en/docs/getting-started/install/_index.md
>  {{% /alert %}}
removed

2023-11-30 23:24 UTC, chrisdoherty4 approved these changes

2023-12-10 21:39 UTC, chrisnegus commented
/cherry-pick release-0.18

2023-12-10 21:42 UTC, merged