Add user facing doc for management-components upgrade
aws/eks-anywhere pull request #7661
Opened 2024-02-21 18:47 UTC by d8660091

*Issue #, if available:*

*Description of changes:*

*Testing (if applicable):*

*Documentation added/planned (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-22 15:39 UTC, chrisnegus reviewed
This reads very well. Just a few wording suggestions.

2024-02-22 15:39 UTC, chrisnegus commented on docs/content/en/docs/clustermgmt/cluster-upgrades/management-components-upgrade.md
> +>**_NOTE:_** `upgrade management-components` sub-command is added in `eksctl anywhere` version `v0.19.0` for all providers. Management components upgrade can only be done through `eksctl-anywhere` cl
```suggestion
>**_NOTE:_** The `upgrade management-components` sub-command is added in `eksctl anywhere` version `v0.19.0` for all providers. Management components upgrades can only be done through the `eksctl anywhere` cli, not through the Kubernetes API.
```

2024-02-22 15:39 UTC, chrisnegus commented on docs/content/en/docs/clustermgmt/cluster-upgrades/management-components-upgrade.md
> +Management components are the k8s resources in an EKSA management cluster that are responsible for managing the EKS-A clusters' lifecycle. Key components include, but are not limited to:
```suggestion
Management components are the Kubernetes resources in an EKS Anywhere management cluster that are responsible for managing the EKS Anywhere cluster's lifecycle. Key components include, but are not limited to:
```

2024-02-22 15:39 UTC, chrisnegus commented on docs/content/en/docs/clustermgmt/cluster-upgrades/management-components-upgrade.md
> +* Tinkerbell services located in a bare metal management cluster.
```suggestion
* Tinkerbell services located in a Bare Metal management cluster.
```

2024-02-22 15:39 UTC, chrisnegus commented on docs/content/en/docs/clustermgmt/cluster-upgrades/management-components-upgrade.md
> +### Why upgrade management-components separately?
```suggestion
### Why upgrade management components separately?
```

2024-02-22 15:39 UTC, chrisnegus commented on docs/content/en/docs/clustermgmt/cluster-upgrades/management-components-upgrade.md
> +The “upgrade cluster” command, when executed against a management cluster, not only upgrades its management components but also initiates a comprehensive upgrade of the management cluster itself. Thi
```suggestion
The `upgrade cluster` command, when executed against a management cluster, not only upgrades its management components but also initiates a comprehensive upgrade of the management cluster itself. This process often entails node replacement and significant operational tasks, which might be deemed risky for some production environments due to the potential of replacing all Kubernetes nodes. 
```

2024-02-22 15:39 UTC, chrisnegus commented on docs/content/en/docs/clustermgmt/cluster-upgrades/management-components-upgrade.md
> +However, to leverage enhancements of newer EKSA version, such as bug fixes in the new management components without the extensive risk, it's advisable to initially upgrade only the management compone
```suggestion
However, to leverage enhancements to newer EKS Anywhere versions, such as bug fixes in the new management components without the extensive risk, it's advisable to initially upgrade only the management components. This step ensures minimal disruption and risk. Subsequently, you can proceed to upgrade the workload cluster at a more convenient time, once you're confident in the stability and readiness of your environment. This strategy provides a more controlled and efficient method to update your cluster's management infrastructure, aligning upgrades with your readiness and risk tolerance levels.
```

2024-02-23 16:10 UTC, csplinter requested changes

2024-02-23 18:05 UTC, csplinter commented on docs/content/en/docs/clustermgmt/cluster-upgrades/management-components-upgrade.md
> +  How to perform management components upgrade for management clusters
How to upgrade EKS Anywhere management components

2024-02-23 18:07 UTC, csplinter commented on docs/content/en/docs/clustermgmt/cluster-upgrades/management-components-upgrade.md
> +>**_NOTE:_** The `upgrade management-components` sub-command is added in `EKS Anywhere` version `v0.19.0` for all providers. Management components upgrades can only be done through the `eksctl anywhe
The `eksctl anywhere upgrade management-components` subcommand was added in EKS Anywhere version `v0.19.0` for all providers. Management component upgrades can only be done through the `eksctl` CLI, not through the Kubernetes API.

2024-02-23 18:11 UTC, csplinter commented on docs/content/en/docs/clustermgmt/cluster-upgrades/management-components-upgrade.md
> +At this point, a new `eksaVersion` custom resource will be available in your management cluster. You can subsequently run a workload cluster upgrade with the `eksctl anywhere upgrade cluster command`
At this point, a new `eksaVersion` custom resource will be available in your management cluster, which means new cluster components that correspond to the `eksaVersion` are available for cluster upgrades.

2024-02-23 18:19 UTC, csplinter approved these changes

2024-02-23 18:22 UTC, merged