Add docs for using Pod IAM with EKS Anywhere
aws/eks-anywhere pull request #898
Opened 2022-01-03 18:05 UTC by mrajashree

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-01-03 18:40 UTC, chrisnegus requested changes
@mrajashree It reads really well. I only have a few small comments. Can you recommend a technical reviewer to have a look at it?

2022-01-03 18:40 UTC, chrisnegus commented on docs/content/en/docs/reference/clusterspec/irsa.md
> +IAM Role for Service Account (IRSA) enables applications running in clusters to authenticate with AWS services using IAM roles. The current solution for leveraging this in EKS Anywhere involves creat
```suggestion
IAM Role for Service Account (IRSA) enables applications running in clusters to authenticate with AWS services using IAM roles. The current solution for leveraging this in EKS Anywhere involves creating your own OIDC provider for the cluster, and hosting your cluster's public service account signing key. The public keys along with the OIDC discovery document should be hosted somewhere that AWS STS can discover it. The steps below assume the keys will be hosted on a publicly accessible S3 bucket. Refer [this](https://docs.aws.amazon.com/AmazonS3/latest/userguide/configuring-block-public-access-bucket.html) doc to ensure that the S3 bucket is publicly accessible.
```
I think "S3" should be capitalized, unless you are specifically referring to the s3 command-line option.

2022-01-03 18:40 UTC, chrisnegus commented on docs/content/en/docs/reference/clusterspec/irsa.md
> +1. Create an s3 bucket to host the public signing keys and OIDC discovery document for your cluster as per [this section](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTE
```suggestion
1. Create an S3 bucket to host the public signing keys and OIDC discovery document for your cluster as per [this section](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md#create-an-s3-bucket). Ensure you follow all the steps and save the `$HOSTNAME` and `$ISSUER_HOSTPATH`.
```

2022-01-03 18:40 UTC, chrisnegus commented on docs/content/en/docs/reference/clusterspec/irsa.md
> +1. Upload the keys.json document to the s3 bucket.
```suggestion
1. Upload the keys.json document to the S3 bucket.
```

2022-01-03 18:40 UTC, chrisnegus commented on docs/content/en/docs/reference/clusterspec/irsa.md
> +1. Follow the [in-cluster installation steps](https://github.com/aws/amazon-eks-pod-identity-webhook#in-cluster) for amazon-eks-pod-identity-webhook. While running the make target, make sure the $KUB
```suggestion
1. Follow the [in-cluster installation steps](https://github.com/aws/amazon-eks-pod-identity-webhook#in-cluster) for amazon-eks-pod-identity-webhook. While running the `make` target, make sure the $KUBECONFIG env var is set to the path of the EKS Anywhere cluster.
```

2022-01-03 18:40 UTC, chrisnegus commented on docs/content/en/docs/reference/clusterspec/irsa.md
> +Change the line to look like the following line. Replace `aud` with `sub` and replace `KUBERNETES_ERVICE_ACCOUNT_NAMESPACE` and `KUBERNETES_SERVICE_ACCOUNT_NAME` with the name of your Kubernetes serv
```suggestion
Change the line to look like the following line. Replace `aud` with `sub` and replace `KUBERNETES_SERVICE_ACCOUNT_NAMESPACE` and `KUBERNETES_SERVICE_ACCOUNT_NAME` with the name of your Kubernetes service account and the Kubernetes namespace that the account exists in.
```
Missing an S?

2022-01-03 18:40 UTC, chrisnegus commented on docs/content/en/docs/reference/clusterspec/irsa.md
> +Refer [this](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html) doc for different ways of configuring one or multiple service accounts through the
```suggestion
Refer to [this](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html) doc for different ways of configuring one or multiple service accounts through the condition operators in the trust relationship.
```

2022-01-03 18:40 UTC, chrisnegus commented on docs/content/en/docs/reference/faq/_index.md
> +along with instructions specific to EKS-Anywhere to enable AWS authentication. Please see the [IRSA reference]({{< relref "../../reference/clusterspec/irsa.md" >}}) for details.
```suggestion
along with instructions specific to EKS Anywhere to enable AWS authentication. Please see the [IRSA reference]({{< relref "../../reference/clusterspec/irsa.md" >}}) for details.
```

2022-01-03 18:47 UTC, chrisnegus commented on docs/content/en/docs/reference/clusterspec/irsa.md
> +```bash
Indent each of the code blocks or sub-lists within numbered lists three spaces. Otherwise the next number will return to 1.

2022-01-03 18:47 UTC, chrisnegus commented on docs/content/en/docs/reference/clusterspec/irsa.md
> +```bash
Indent bash block three spaces.

2022-01-03 18:57 UTC, chrisnegus commented on docs/content/en/docs/reference/clusterspec/irsa.md
> +		For Identity provider, choose the auto selected Identity Provider URL for your cluster.
```suggestion
      * For Identity provider, choose the auto selected Identity Provider URL for your cluster.
      * For Audience, choose sts.amazonaws.com.
```
I think you are looking for something like this. I think you can indent the nested numbered list 3 spaces, then indent the two bullets in another two spaces. You may have to play with it a bit to get it to work.

2022-01-04 10:35 UTC, mrajashree commented
> @mrajashree It reads really well. I only have a few small comments. Can you recommend a technical reviewer to have a look at it?

@chrisnegus thanks for reviewing, I'll request a review from @micahhausler

2022-01-05 15:26 UTC, micahhausler requested changes
2 minor changes, thanks!

2022-01-05 15:26 UTC, micahhausler commented on docs/content/en/docs/reference/clusterspec/irsa.md
> +Change the line to look like the following line. Replace `aud` with `sub` and replace `KUBERNETES_ERVICE_ACCOUNT_NAMESPACE` and `KUBERNETES_SERVICE_ACCOUNT_NAME` with the name of your Kubernetes serv
```suggestion
Change the line to look like the following line. Replace `aud` with `sub` and replace `KUBERNETES_SERVICE_ACCOUNT_NAMESPACE` and `KUBERNETES_SERVICE_ACCOUNT_NAME` with the name of your Kubernetes service account and the Kubernetes namespace that the account exists in.
```

2022-01-05 15:48 UTC, micahhausler approved these changes
/LGTM

2022-01-06 17:15 UTC, micahhausler commented
/lgtm

2022-01-06 17:18 UTC, merged

2022-01-12 15:53 UTC, mrajashree commented
https://github.com/aws/eks-anywhere/issues/601